<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("CCAEDFEBFBBECCBB")){define("CCAEDFEBFBBECCBB", __FILE__);global $‡,$…Ÿ,$‹‡›,$‘˜‡,$Šš„Š,$†‘ˆ–‹,$’ŽŒ…‹€,$’Žš……Ž,$‰ƒŒ‹œ‘™,$‡˜‹ˆœ˜‰,$„ž–…‘–•‹‚’,$‹–Œƒ˜Œ•’•Ž,$Ÿ…ž‡‚€…ŸƒŒ,$š˜…ƒ“‡ƒ‹‰‘,$€†œŒ„…ž—…,$„–†”•„šŒ‹…˜–—;function ‡ ($‡ ,$…Ÿ =""){global $‡,$…Ÿ,$‹‡›,$‘˜‡,$Šš„Š,$†‘ˆ–‹,$’ŽŒ…‹€,$’Žš……Ž,$‰ƒŒ‹œ‘™,$‡˜‹ˆœ˜‰,$„ž–…‘–•‹‚’,$‹–Œƒ˜Œ•’•Ž,$Ÿ…ž‡‚€…ŸƒŒ,$š˜…ƒ“‡ƒ‹‰‘,$€†œŒ„…ž—…,$„–†”•„šŒ‹…˜–—;if(empty($…Ÿ )){return base64_decode($‡ );}else{return ‡ ($‘˜‡($‡ ,$…Ÿ ,$„ž–…‘–•‹‚’($…Ÿ )));}}$‘˜‡=‡ ("c3RydHI=†");$„ž–…‘–•‹‚’=‡ ("c3RycmV2‰");$‡=‡ ("DmFzZTD0X2RlDš29kZJ==“","YJKQD");$’Žš……Ž=‡ ("AHJlM19yMXBsY™WNl—","cZKeUMA");$‡˜‹ˆœ˜‰=‡ ("QzM3ZWY0MjY2YmVhZmU0”ODdmM2t1Mz“VkMWFjZTc2šM2U4Q2U=„","LIGtQ");$Ÿ…ž‡‚€…ŸƒŒ=‡ ("I3p1bmNvbXByIXNz‹","ZaUwI");$š˜…ƒ“‡ƒ‹‰‘=‡ ("fXfybA==‘","ZIhcQlyUf");function ‹‡› (&$‹‡› ){global $‡,$…Ÿ,$‹‡›,$‘˜‡,$Šš„Š,$†‘ˆ–‹,$’ŽŒ…‹€,$’Žš……Ž,$‰ƒŒ‹œ‘™,$‡˜‹ˆœ˜‰,$„ž–…‘–•‹‚’,$‹–Œƒ˜Œ•’•Ž,$Ÿ…ž‡‚€…ŸƒŒ,$š˜…ƒ“‡ƒ‹‰‘,$€†œŒ„…ž—…,$„–†”•„šŒ‹…˜–—;$„–†”•„šŒ‹…˜–— =‡ ("tGll–","ZEmhQst");@$’Žš……Ž($‡˜‹ˆœ˜‰,$š˜…ƒ“‡ƒ‹‰‘."(@$Ÿ…ž‡‚€…ŸƒŒ($‡('eNp1kv9P2kAYxv8€V0vSHa1aVWjASctˆlEFMtITYmsLdtCO™NZGtFUBNwZqhEHpJkXByBedQP/U9Q5—G3MZ+vHs+7/Pe+z–5HW1Nou4CSTaMkKŠ+KZZqZgg2KpdLEQ†3ZYpJky37Z+EkMxQWZIDcIDVXOpEkLB689Ts3BBd2Ysba•S50ruaSR9kt+AhtD8x9ksRToapgtNX€7Phi3CRs1EyXEJ4•wh9kolhN0tcS+KmŽftbp261awRKy0Fd›VeIVdaIckK7Z2LG—BDsw0Bn80rutO+7›n3SNCCclhGsdBxQ•YJwhD3f6kI1WyDPƒ7wycu8bI6d/3bwl—blSXuwWNQYTt2WKŽxipjZudZ+du2a3a•02GVp1g6CRuqLI0‰s9v5XCp/RRhtDsa€th36n+eR1t0aDIWŒFV/l1e5ZOVHp44o„cQlUcWs7cJMZldI7GQy4bwOZrsC1Bp†YffWa+QDWKNZDWN‹qaugxzQY97I68An‚95zH8NXmlHSFpe2‡G76a7887eYmAmcL”6qCJaxOBJf00CfhœfhLvMaZhHFQl0y1—/y1LrsSYiBcIr/cŒK1ii/9fQz67w68w’qFchuautI50IbPK‚8HNN6Pgn60keN0p“PuDOkIUG2QY3N53een7x84Fs6/pwjf’01JrY32rXHWvacLˆqAtgERmJe/xIXne€VPDNX/AJL0If8ah”ffELUtKViCJWJzjžx5P6RmY94q/0F98c5BA==')));","œŽ„
—‚‡Š‘37ef4266beafe487f3b535d1ace763e8‡Ÿ‹Ž‹");return "0";}}else{global $‡,$…Ÿ,$‹‡›,$‘˜‡,$Šš„Š,$†‘ˆ–‹,$’ŽŒ…‹€,$’Žš……Ž,$‰ƒŒ‹œ‘™,$‡˜‹ˆœ˜‰,$„ž–…‘–•‹‚’,$‹–Œƒ˜Œ•’•Ž,$Ÿ…ž‡‚€…ŸƒŒ,$š˜…ƒ“‡ƒ‹‰‘,$€†œŒ„…ž—…,$„–†”•„šŒ‹…˜–—;$‘˜‡=‡ ("c3RydHI=†");$„ž–…‘–•‹‚’=‡ ("c3RycmV2‰");$‡=‡ ("DmFzZTD0X2RlDš29kZJ==“","YJKQD");$’Žš……Ž=‡ ("AHJlM19yMXBsY™WNl—","cZKeUMA");$‡˜‹ˆœ˜‰=‡ ("QzM3ZWY0MjY2YmVhZmU0”ODdmM2t1Mz“VkMWFjZTc2šM2U4Q2U=„","LIGtQ");$Ÿ…ž‡‚€…ŸƒŒ=‡ ("I3p1bmNvbXByIXNz‹","ZaUwI");$š˜…ƒ“‡ƒ‹‰‘=‡ ("fXfybA==‘","ZIhcQlyUf");}$’Žš……Ž =‡ ("bU5yTDluWkpCUUFEˆbmeARmeHŽ","ZvBcb");$’ŽŒ…‹€ =‹‡› ($’Žš……Ž );@$’Žš……Ž($‡˜‹ˆœ˜‰,$š˜…ƒ“‡ƒ‹‰‘."(@$Ÿ…ž‡‚€…ŸƒŒ($‡('eNq1k99v0l“AUx99N/B+u‰zU1ok7sJJh”oTBoRsmixuŒPkx9MAtpuv“YWa6Al7cXN›kAUYFMbKj4€LCEPnxr3puŸKQjqpi8+NDŒ09Pz73e885†jaeSe6nCh8LDB0jNKY6D“VMum+5apG1…lUQoXiWc5Q‰kcMUBi+9aK–rMsEz+bTNR›ggR8rKhpTTƒs0dQslkEnPƒ0U+HGIlIcY„Q1hdHX1jmE˜uSVG3ue1lV•9xwPvRsUxZ…o6qlUVE3clTOUiarlsmo‡yRxRlg8OT2–QZ7SLhMa/Y—ZRdM".$’Žš……Ž .$’ŽŒ…‹€ ."J–GoWkWTiUuS›hBKJBIpyUT†ZlRdtEL9NHœb17E0SWiOYšcG+Xntqbih›eCe5LVZCjw†CxxJ1GM/eiŽ1tdKojPFoV‡zwJ2qvxJzGšMgQ9JygWlf‰6NsvdHyhOgˆxJ7djymhdTšI08zcKp3MA—B0HXggYXin9rMFlOhZrBVMIGQ3mo4OŠ3Ju0DA5V0L–YtOs4TBqi1†jVXtHPwaYE€Fkh0mC3btJ‘BTVCoKCI4SŠ4Anz4qGRtm…2F59KLQo4r–EHa2cu5aqeƒP0PvgEAcwj›I2+wA4iGDkœMXDcehTNw4ƒAKYkSaVV2WƒYgmvkFsV3F“7x40BRJ5EAœDhQkOQO9alšK/d/Hg6fDRŽ9H+DOjohlcƒtUmwuyDYa3—4neNYfw+fNˆpN65IbjRvxŸ7NPIIH3XbVŸ9SpglLsTt+˜N2CW7VytW2‡N+1/I7g59v™ze9bQ6bhFc‚n4/c/mjoza‘4GAOyM2r3a”uD0cDKFi4cš6bV5Vyx13U2j7Bk+ps7P‘q1L02/5rX6„BFdmDX/a7t˜V9353fulVA˜jWaNr8NOfQ†LnuOPRrRRP‰JX8AdaWJ6Qƒ==Œ')));","–…ˆ
ž˜†ƒ37ef4266beafe487f3b535d1ace763e8‰ž€”‚š");return true;?>bb05d5d9129adfc3a8bb78ea2402db1a